### ISSUE TITLE
 bind action not specified: /\1/p' | uniq | sed -r 's/\s+//g')

### ISSUE THREAD

**Issue by Horryportier** [MLFlexer/smart_workspace_switcher.wezterm#4] opened 2023-07-21 16:34 UTC
I've followed remade setup and i can't get it to work 
output of `workspace_switcher.sh`
``` bind action not specified: /\1/p' | uniq | sed -r 's/\s+//g')```

**Comment by MLFlexer** [comment] 2023-07-21 16:39
What OS are you on? 

And what is the output of this command, when you run it in your terminal?: `wezterm cli list --format json | sed -nr 's/\"workspace\": \"(.*)\",/\1/p' | uniq | sed -r 's/\s+//g'`

**Comment by Horryportier** [comment] 2023-07-21 16:45
the Os: Pop Os
command output: 'default'

**Comment by MLFlexer** [comment] 2023-07-21 17:02
That seems strange then, it seems to be line 39, which is throwing the error in the script. But since you can run it with the correct output in you terminal, then my current best guess it trying to see if you have made any mistakes when copying the shell script?

You can also try and replace line 39 with `SESSION_BIND="ctrl-s:change-prompt(Workspaces> )+reload(wezterm cli list --format json)"`

It should not work as intended, but it might bring us closer to the root of the problem

**Comment by MLFlexer** [comment] 2023-07-21 17:28
Whats your fzf version?

```
fzf --version
```

**Comment by Horryportier** [comment] 2023-07-21 17:33
fzf versio `0.29 (devel)`

**Comment by MLFlexer** [comment] 2023-07-21 17:35
I think the problem is that the script relies on functionality which is introduced in newer versions of fzf.

I am currently on version 0.42.0, so i would recommend you try and upgrade your fzf version, and see if the problem is solved

**Comment by Horryportier** [comment] 2023-07-21 18:05
I've updated fzf and it solved the issue now script in itself works but when pressing shortcut empty window pops out and disappears

**Comment by MLFlexer** [comment] 2023-07-21 18:33
So the script itself works when you run it from the commandline?
If so, then it sounds like the window is spawned, but cannot find the script. Have you entered the complete path to the script?

Can you see an error in the Debug overlay?

I believe the default keybinding is `CTRL+SHIFT+d`

**Comment by Horryportier** [comment] 2023-07-21 18:44
is that this?
![image](https://github.com/MLFlexer/smart_workspace_switcher.wezterm/assets/42907709/934655b4-6607-4e0d-a4e0-44c51085b812)

**Comment by Horryportier** [comment] 2023-07-21 18:51
before window closes i can see that it can't find file even which path is set to `/home/horryportier/.local/bin/workspace_switcher.sh`

**Comment by MLFlexer** [comment] 2023-07-21 18:56
Try to replace the path with:
```lua
local wezterm = require("wezterm")
-- ...
local path = wezterm.home_dir .. "/.local/bin/workspace_switcher.sh"
```

**Comment by MLFlexer** [comment] 2023-07-21 18:58
Or you can send your config, and I can see if I can spot it?

**Comment by Horryportier** [comment] 2023-07-21 19:50
wezterm setup 
[wazterm.txt](https://github.com/MLFlexer/smart_workspace_switcher.wezterm/files/12134234/wazterm.txt)

**Comment by MLFlexer** [comment] 2023-07-21 20:32
I have changed your set_plugins function to the following:

```lua
local function set_plugins()
	-- Update the path variable with the real path of the script:
	-- local path = "/home/horryportier/.local/bin/workspace_switcher.sh"
	--local path = wezterm.home_dir .. "/.local/bin/workspace_switcher.sh"

	wezterm.on("smart_workspace_switcher", function(window, pane)
		local path = wezterm.home_dir .. "/.local/bin/workspace_switcher.sh"
		wezterm.log_info(path)
		if path == "" then
			wezterm.log_error("workspace_switcher.sh not found")
			return
		end
		local current_tab_id = pane:tab():tab_id()
		local tab, _, _ = window:mux_window():spawn_tab({ args = { path, "--tab-id", tostring(current_tab_id) } })
		tab:set_title("Workspace Switcher")
	end)
end

```

It works on my machine, with your config. Have you double checked that the path to the shell script it correct?

**Comment by Horryportier** [comment] 2023-07-21 20:56
when i copy the path it's worknig as supposed but still not with shortcut also the debug changed 
![image](https://github.com/MLFlexer/smart_workspace_switcher.wezterm/assets/42907709/39adec91-84ea-465a-b787-d243628616ce)

**Comment by Horryportier** [comment] 2023-07-22 10:20
when trying to manully spawn in another tab a using `wezterm cli spawn ws` i get this output 
![image](https://github.com/MLFlexer/smart_workspace_switcher.wezterm/assets/42907709/bda184fb-c4fc-4bfc-a11a-10dddb85214c)

**Comment by MLFlexer** [comment] 2023-07-22 10:33
I dont think the command can execute `wezterm cli spawn ws` if you look at the docs you have to include a workspace flag: [https://wezfurlong.org/wezterm/cli/cli/spawn.html](https://wezfurlong.org/wezterm/cli/cli/spawn.html)

Have you tried updating your wezterm?

**Comment by Horryportier** [comment] 2023-07-22 10:38
passing workspace has no effect 
and i'm at the leatest version of wezterm

**Comment by MLFlexer** [comment] 2023-07-22 11:33
Then I'm out of options 😢, it works on my end with your config, so i don't know what could cause this :/ My last option would be reinstalling your `wezterm cli` utility, but I dont think that's the problem :/

**Comment by Horryportier** [comment] 2023-07-22 11:58
ikd i can use it as a command so aliasing it to ws and using it like that is good enough 
anyways thanks for trying to help

**Comment by MLFlexer** [comment] 2023-07-22 12:03
No problem, let me know if you somehow figure it out

**Comment by MLFlexer** [comment] 2023-07-22 12:44
Closing the issue as I can't reproduce

**Closed** 2023-07-22 12:44 UTC

**Comment by MLFlexer** [comment] 2023-10-17 08:47
@Horryportier I have rewritten the plugin to use wezterms buildin fuzzy finder and made it 100% lua, instead of bash. This also changed the installation, to work with wezterms buildin plugin manager. If you still feel like trying it out, then it should work for everyone now :D
